# 异常处理(恐慌panic)
## defer + recover

``` go
func div(a int, b int) (div int) {
	defer func() {
		//调用recover内置函数，可以捕获错误
		err := recover()
		// 如果没有捕获错误，返回值为零值：nil
		if err != nil {
			fmt.Println("div捕获到错误", err)
		}
	}() // 加上匿名函数的调用
	div = a / b
	return
}
```

## 自定义错误

```go

```